services:
  api:
    platform: linux/amd64
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 3000
    command: >
      sh -c "
      yarn prisma migrate deploy &&
      yarn start:prod
      "
    volumes:
      - .data/picmory/uploads:/app/uploads
