version: "3"

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    env_file:
      - .env.web
    ports:
      - "81:81"
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./.data/nginx:/var/log/nginx

  database:
    image: postgres:16.4
    restart: unless-stopped
    env_file:
      - .env.database
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data

  api:
    platform: linux/amd64
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env.api
    expose:
      - 3000
    command: >
      sh -c "
      yarn prisma migrate deploy &&
      yarn start:prod
      "
    depends_on:
      - database
