name: picmory
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animate_do: ^3.3.3
  chewie: ^1.7.5
  custom_refresh_indicator: ^3.0.0
  dio: ^5.4.0
  extended_image: ^8.2.0
  firebase_analytics: ^10.8.9
  firebase_core: ^2.24.2
  firebase_remote_config: ^4.3.17
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.10
  flutter_secure_storage: ^9.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  go_router: ^13.0.1
  google_sign_in: ^6.2.1
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.7
  intl: ^0.19.0
  mobile_scanner: ^4.0.0
  package_info_plus: ^5.0.1
  path_provider: ^2.1.2
  provider: ^6.1.1
  shimmer: ^3.0.0
  sign_in_with_apple: ^5.0.0
  smooth_page_indicator: ^1.1.0
  solar_icons: ^0.0.5
  supabase_flutter: ^2.2.0
  table_calendar: ^3.1.1
  url_launcher: ^6.2.6
  video_player: ^2.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_oss_licenses: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  fonts:
    - family: SUITE-Variable
      fonts:
        - asset: assets/fonts/SUITE-Variable.ttf

  assets:
    # 환경변수
    - .env
    # Icons
    - assets/icons/
    # Images
    - assets/images/camera_filter/
    # Logo
    - assets/logo.png

flutter_launcher_icons:
  image_path: 'assets/logo.png'
  ios: true
  remove_alpha_ios: true
  # android: "launcher_icon"
  # min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: '#ffffff'
  image: assets/logo.png
  ios: true
