name: Deploy with Self-Hosted Runner

on:
  pull_request:
    paths:
      - "server/**"
    types: [closed]
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    # main 브랜치로의 PR이 머지된 경우에만 실행
    if: github.event.pull_request.merged == true

    steps:
      - name: Pull latest changes
        run: |
          git pull origin main
        working-directory: ${{ secrets.SOURCE_PATH }}

      - name: Install dependencies
        run: |
          yarn install
        working-directory: ${{ secrets.SOURCE_PATH }}

      - name: Build
        run: |
          yarn build
        working-directory: ${{ secrets.SOURCE_PATH }}

      - name: Reload server
        run: |
          yarn pm2:reload
        working-directory: ${{ secrets.SOURCE_PATH }}
